### ISSUE TITLE
yEd example file is missing

### ISSUE THREAD

**Issue by JanSHUP** [bask185/ArduinoToolchain#1]
Hey,

this is a really interesting approach and I ould like to give it a try. In Dependencies you wrote: "One such a state diagram is included in this repository so you can test the scripts before you instal yEd." however I cannot find the yEd file in your repository. 

Would you mind to upload it again?

best regards and thanks, Jan

**Comment by bask185** [comment]
Hi Jan,

I cannot find it either, it is not first time I deleted something by mistake. I will add a new folder with a few examples later today. In the mean time you can take a look at the following link

https://github.com/bask185/gameExample
[https://avatars0.githubusercontent.com/u/41281968?s=400&v=4]<https://github.com/bask185/gameExample>
bask185/gameExample<https://github.com/bask185/gameExample>
Contribute to bask185/gameExample development by creating an account on GitHub.
github.com

This is a project which is created using the build scripts. You can upload it to any arduino and play a simple game via the terminal using Putty. This folder also contains the sub-folder 'stateDiagrams' which does have an yEd file for you to test with.

It has been a while that I worked on my project. Now I am working a lot with VS Code and I have learned to program arduino's from within VS code itself. For this I am going to add a tasks.json file to any assembled project. It allows you to program an arduino by a single press on F6. If a user wants to do the same and ditch the arduino IDE, then he can.
________________________________
Van: JanSHUP <notifications@github.com>
Verzonden: woensdag 8 juli 2020 23:18
Aan: bask185/State-Machine-Scripts <State-Machine-Scripts@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [bask185/State-Machine-Scripts] yEd example file is missing (#1)


Hey,

this is a really interesting approach and I ould like to give it a try. In Dependencies you wrote: "One such a state diagram is included in this repository so you can test the scripts before you instal yEd." however I cannot find the yEd file in your repository.

Would you mind to upload it again?

best regards and thanks, Jan
